### ISSUE TITLE
[BUG] Exit housing menu not opening?

### ISSUE THREAD

**Issue by NoobySloth** [qbcore-framework/qb-houses#183]
**Describe the bug**
Menu doesn't open upon trying to exit

**To Reproduce**
Try to exit the house

**Expected behavior**
open menu to let you out

**Screenshots**
![image](https://user-images.githubusercontent.com/6962192/165976325-b6cf6b3a-6712-4ce3-aa44-f206f893c77f.png)

**Questions (please complete the following information):**
 - When you last updated: most recent
 - Are you using custom resource? which ones? not for housing
 - Have you renamed `qb-` to something custom? no

**Additional context**
Upon inspecting, I cannot find the `qb-houses:client:OpenClientOptions` trigger anywhere in qb? This is being searched through the whole of my server
![image](https://user-images.githubusercontent.com/6962192/165976592-0dc4b7fb-8d02-4472-a701-612a6b4a2af7.png)

**Comment by MadManDanCat** [comment]
I also get this the houses is kinda messed up a bit

**Comment by nzkfc** [comment]
We are also having this issue since updating, heaps of players unable to get out of houses.

Also seems that doors are now set to unlocked (https://i.imgur.com/bW4jGHi.png) even though you cannot enter (I have no key in this screenshot but I should be able to enter if it's unlocked? Just does nothing)

**Comment by nzkfc** [comment]
This is really killing our server, admins having to constantly pull people out when they get stuck.

**Comment by MadManDanCat** [comment]
Yeah they broke a lot of stuff with the new updates and just won't fix it we bought a new housing script and pretty much replaced everything  in the base qbcore as it's all ass it's the same as qbus mostly

**Comment by nzkfc** [comment]
So they are doing security updates at the moment, then working on these
issues, but some of these in houses and garages needs fixing sooner.

Your comment on the framework isn't really needed, you can use what you
want too, qb-core was born out of stopping the leak crap that was happening
with qbus. That's why it is similar, it's just now open source and
controlled so everyone can enjoy it. She's relatively young still and the
team is doing all they can to progress it and make it better, so if you
know how to fix things please do send PR to help out.

**Comment by rhyfii** [comment]
I came up with a fix that seems to be working with a decent amount of testing, however you'll need to test for yourself. I tested with 3 people entering and leaving via logout event, F8 quit, as well as server restart. 

Replace the DeleteHousesTargets() with the following;

```
local function DeleteHousesTargets()
    if Config.Targets and next(Config.Targets) then
        for id, target in pairs(Config.Targets) do
            if not string.find(id, "Exit") then
                target.zone:destroy()
                Config.Targets[id] = nil
            end
        end
    end
end
```

**Comment by nzkfc** [comment]
Noice, hopefully this is the answer, maybe do a PR so the team can see it
better when they come to it?

**Comment by rhyfii** [comment]
https://github.com/qbcore-framework/qb-houses/pull/190#issue-1249239942

**Comment by nzkfc** [comment]
Here is an example of how some of our players have to get out of their house lol, using garages because the polyzone is that close.

https://medal.tv/clips/msPh60v5PIi9g/vpZpalwxN?invite=cr-MSxzTVYsNjIyMDMxMDQs

**Comment by nzkfc** [comment]
So this house is our #1 problem maker, can see the giant garage polyzone for the house garage that realestate set, then the house polyzone is within that garage zone (not sure if thats an issue?) and when you go into the house you get stuck and cannot get out. The door polyzone that pops up at the end to get out doesn't seem to occur on our production server (160 players average) but on dev it's fine and seems to work?

https://drive.google.com/file/d/15ouKSDS7uQVzBBgBXisBW-ElQuQgOZWR/view?usp=sharing
